//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_cs_library
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class ksiazka
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ksiazka()
        {
            this.wypozyczenie = new ObservableCollection<wypozyczenie>();
        }
    
        public int ksiazka_id { get; set; }
        public Nullable<int> autor_id { get; set; }
        public string tytul { get; set; }
        public System.DateTime data_wydania { get; set; }
        public string wydawnictwo { get; set; }
        public Nullable<int> liczba_stron { get; set; }
    
        public virtual autor autor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<wypozyczenie> wypozyczenie { get; set; }
    }
}
