//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_cs_library
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bibliotekaEntities : DbContext
    {
        public bibliotekaEntities()
            : base("name=bibliotekaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<autor> autor { get; set; }
        public virtual DbSet<klient> klient { get; set; }
        public virtual DbSet<ksiazka> ksiazka { get; set; }
        public virtual DbSet<wypozyczenie> wypozyczenie { get; set; }
    }
}
