//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_cs_library
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class wypozyczenie
    {
        public int wypozyczenie_id { get; set; }
        public Nullable<int> ksiazka_id { get; set; }
        public Nullable<int> klient_id { get; set; }
        public System.DateTime data_wypozyczenia { get; set; } = DateTime.Now;
        public Nullable<System.DateTime> data_oddania { get; set; }
    
        public virtual klient klient { get; set; }
        public virtual ksiazka ksiazka { get; set; }
    }
}
